### ISSUE TITLE
Same color on multiple object properties.

### ISSUE THREAD

**Issue by danielcostarosenthal** [christopherafbjur/vscode-theme-onedarker#4]
I'd appreciate if you could add the following features:

- [ the color changes when it deals with an imported module ] 

- [ the color changes when accessing multiple values on an object ] 

Screenshots attached where we can see this in action with VStudio's Dark+ theme.

Much appreciated.

https://user-images.githubusercontent.com/71814817/152434403-26e2db78-b282-49c4-be2d-a20459fa0b84.png
https://user-images.githubusercontent.com/71814817/152434409-bc906d4f-9bbc-49fc-a2ab-0bac93aba9e8.png
https://user-images.githubusercontent.com/71814817/152434410-320f63a5-0fe4-4f3d-ac5e-fdb7ef4b2ca3.png
https://user-images.githubusercontent.com/71814817/152434414-8644f5c1-e1ad-4e4d-94f8-c601c3a0eed0.png

**Comment by christopherafbjur** [comment]
Hi @danielcostarosenthal I've just looked into this and found some inconsistencies based on your examples. How ever I was not able to re-produce the behavior shown within your examples images of the Atom One Darker (Version 2.0.6) as can be seen here (except for the template literal):
<img width="490" alt="image" src="https://user-images.githubusercontent.com/13018273/153455294-c967ffe3-2041-43c5-b783-5c4b84379db1.png">


I also want to underline that this theme is based out of [Atom's](https://atom.io/) One Dark theme, so in order for nested objects to behave the same way as Dark+, shown in your comparison screenshots, we'd be breaking the rules of the original theme. Let me show you:

Atom One Dark (Original Theme, using  [Atom](https://atom.io/))
<img width="532" alt="Screenshot 2022-02-10 at 17 09 05" src="https://user-images.githubusercontent.com/13018273/153454981-29f02303-23ad-4fae-86a1-a27032bb9e92.png">

Atom One Darker (Latest version 2.1.0, using Vscode)
<img width="550" alt="Screenshot 2022-02-10 at 17 08 50" src="https://user-images.githubusercontent.com/13018273/153455112-01a65df3-0513-4e59-8bac-c236b2a6cf94.png">

A sidenote here is that in VSCode, we're unable to highlight imported modules differently than other objects. This seem to be a limitation in VSCode/Textmate. [Atom](https://atom.io/) One Dark doesn't seem to handle imported modules differently.

Also as can be seen in the examples above, [Atom](https://atom.io/) handles Pascal Cased objects differently which is the reason for `Proptypes` and `Tokens` being "yellow" in the example. This was something that I originally tried to solve in version 2.0.6 but understood now while checking is not possible due to VSCode Textmate limitations.

This limitation can however be resolved by implementing custom TextMate grammars, how ever this seem to be an advanced concept which seem difficult to handle and will require time to investigate.



With that said, please go ahead and try [version 2.1.0](https://marketplace.visualstudio.com/items?itemName=christopherafbjur.vscode-theme-onedarker) to see if the extension behaves more in line with what you describe in this issue and what I've explained here. If not, please use the Command Palette and run `Inspect Editor Tokens and Scopes` and show me the scopes which seem incorrect.

**Comment by danielcostarosenthal** [comment]
Hi @christopherafbjur, thanks a lot for your time and investigation you did into this matter.
Unfortunately it's not working not even after updating. As you eloquently put it: it's a VS Code limitation.
